name: Daily Trading Pipeline

on:
  schedule:
    - cron: '0 3 * * *'   # runs 8:00 AM Sri Lanka time (UTC+5:30)
  workflow_dispatch:        # lets you trigger it manually too

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python src/pipline.py
        env:
          NEWS_API_KEY: ${{ secrets.edea65c40c0a4e56be20d4e7902848db }}
          DB_PASSWORD: ${{ secrets.hpHhMq1dFfEy7a0ekTF4 }}
          R2_ACCOUNT_ID: ${{ secrets.90f101094655ba118e505204d5556a70 }}
          R2_ACCESS_KEY: ${{ secrets.b8146b9ae352d8d42c2fb35c0070f5fa }}
          R2_SECRET_KEY: ${{ secrets.5cc215eae819b196916148be98fb0d6524714ebabee5fc607652d02842e6b98f }}
          R2_BUCKET: ${{ secrets.goyum-trading-data }}
          SUPABASE_DB_URL: ${{ secrets.postgresql://postgres.xrnntqvzefodjmmfpqmq:trading@#$1618@aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres }}
